name: Python application

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write # Needed for softprops/action-gh-release
  
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        architecture: "x64"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run PyInstaller
      run: |
        python -m PyInstaller --onefile convert-clipboard-x-to-vxtwitter.py
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: convert-clipboard-x-to-vxtwitter
        path: convert-clipboard-x-to-vxtwitter.exe
      
    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          convert-clipboard-x-to-vxtwitter.exe
    
