name: Python application

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write # Needed for softprops/action-gh-release
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@v0.1.2
      with:
        path: src

    - uses: actions/upload-artifact@v3
      with:
        name: my-exe
        path: src/dist/windows
        
    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          src/dist/windows
    
